eureka:
  client:
    service-url:
      defaultZone: http://localhost:8076/eureka
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8099

spring:
  application:
    name: "product-webapp"

  security:
    oauth2:
      client:
        registration:
          google:
            clientName: Google
            clientId: 978849933216-dtfgqe8cv8g6n6t6q6pm6jtr82o62clg.apps.googleusercontent.com
            clientSecret: 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

