eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true


server:
  port: 8079

spring:
  application:
    name: api-gateway

  cloud:
    config:
      import-check:
        enabled: false

    compatibility-verifier:
      enabled: false
    gateway:

      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service(?<segment>/?.*), $\{segment}


        - id: authentication-service
          uri: http://localhost:8082
          predicates:
            - Path=/authentication-service/**
          filters:
            - RewritePath=/authentication-service(?<segment>/?.*), $\{segment}

        - id: product-service
          uri: http://localhost:8084
          predicates:
            - Path=/product-service/**
          filters:
            - RewritePath=/product-service(?<segment>/?.*), $\{segment}


        - id: order-service
          uri: http://localhost:8088
          predicates:
            - Path=/order-service/**
          filters:
            - RewritePath=/order-service(?<segment>/?.*), $\{segment}

        - id: slot-service
          uri: http://localhost:8087
          predicates:
            - Path=/slot-service/**
          filters:
            - RewritePath=/slot-service(?<segment>/?.*), $\{segment}


        - id: payment-service
          uri: http://localhost:8001
          predicates:
            - Path=/payment-service/**
          filters:
            - RewritePath=/payment-service(?<segment>/?.*), $\{segment}

        - id: email-service
          uri: http://localhost:8089
          predicates:
            - Path=/email-service/**
          filters:
            - RewritePath=/email-service(?<segment>/?.*), $\{segment}

        - id: helpdesk-service
          uri: http://localhost:8086
          predicates:
            - Path=/helpdesk-service/**
          filters:
            - RewritePath=/helpdesk-service(?<segment>/?.*), $\{segment}







